<?php
declare(strict_types=1);
require dirname(__DIR__) . '/platform-bootstrap.php';
if (!platform_installed()) { header('Location: /install.php'); exit; }
$error='';
if(isset($_GET['logout'])){session_destroy();header('Location: /admin/');exit;}
if(empty($_SESSION['admin_id']) && $_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='login'){
    verify_csrf(); $email=strtolower(trim((string)($_POST['email']??''))); $password=(string)($_POST['password']??'');
    $q=db()->prepare('SELECT * FROM admins WHERE email=? LIMIT 1');$q->execute([$email]);$admin=$q->fetch();
    if($admin && password_verify($password,$admin['password_hash'])){session_regenerate_id(true);$_SESSION['admin_id']=$admin['id'];$_SESSION['admin_name']=$admin['name'];header('Location: /admin/');exit;}
    $error='Identifiants incorrects.';
}
if(empty($_SESSION['admin_id'])):
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administration LINKSTECH</title><style>*{box-sizing:border-box}body{margin:0;background:#071a2c;font-family:Arial;min-height:100vh;display:grid;place-items:center}.box{width:min(430px,92%);background:#fff;padding:35px;border-radius:16px}h1{margin-top:0}label{display:block;font-weight:bold;margin:15px 0 7px}input{width:100%;padding:13px;border:1px solid #dfe6eb;border-radius:8px}button{width:100%;margin-top:20px;padding:14px;border:0;border-radius:8px;background:#176bff;color:#fff;font-weight:bold}.error{color:#a21b1b}</style></head><body><form class="box" method="post"><h1>Espace administrateur</h1><p>Gestion des demandes, profils et opportunités LINKSTECH.</p><?php if($error):?><p class="error"><?=e($error)?></p><?php endif;?><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="login"><label>E-mail</label><input type="email" name="email" required><label>Mot de passe</label><input type="password" name="password" required><button>Se connecter</button></form></body></html><?php exit; endif;
admin_required();
$allowedRequest=['new','in_progress','connected','closed'];$allowedOrg=['pending','approved','rejected'];$allowedOpp=['draft','published','closed'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='request_status' && in_array($_POST['status']??'',$allowedRequest,true)){db()->prepare('UPDATE contact_requests SET status=? WHERE id=?')->execute([$_POST['status'],(int)$_POST['id']]);}
 if($action==='org_status' && in_array($_POST['status']??'',$allowedOrg,true)){db()->prepare('UPDATE organizations SET status=? WHERE id=?')->execute([$_POST['status'],(int)$_POST['id']]);}
 if($action==='opp_status' && in_array($_POST['status']??'',$allowedOpp,true)){db()->prepare('UPDATE opportunities SET status=? WHERE id=?')->execute([$_POST['status'],(int)$_POST['id']]);}
 if($action==='create_opportunity'){
  $title=clean_text($_POST['title']??'',220);$cat=clean_text($_POST['category']??'',30);$org=clean_text($_POST['organization']??'',180);$country=clean_text($_POST['country']??'',100);$description=clean_text($_POST['description']??'',3000);$email=clean_text($_POST['email']??'',190);$deadline=$_POST['deadline']?:null;
  if($title&&in_array($cat,['market','service','funding','partnership','training'],true)&&$org&&$country&&$description){db()->prepare('INSERT INTO opportunities(title,category,organization_name,country,description,contact_email,deadline,status) VALUES(?,?,?,?,?,?,?,?)')->execute([$title,$cat,$org,$country,$description,$email?:null,$deadline,'published']);}
 }
 header('Location: /admin/?section='.urlencode((string)($_GET['section']??'dashboard')));exit;
}
$section=$_GET['section']??'dashboard';
$counts=['requests'=>(int)db()->query("SELECT COUNT(*) FROM contact_requests WHERE status='new'")->fetchColumn(),'organizations'=>(int)db()->query("SELECT COUNT(*) FROM organizations WHERE status='pending'")->fetchColumn(),'opportunities'=>(int)db()->query("SELECT COUNT(*) FROM opportunities WHERE status='published'")->fetchColumn()];
$requests=$section==='requests'?db()->query('SELECT * FROM contact_requests ORDER BY created_at DESC LIMIT 200')->fetchAll():[];
$organizations=$section==='organizations'?db()->query('SELECT * FROM organizations ORDER BY created_at DESC LIMIT 200')->fetchAll():[];
$opportunities=$section==='opportunities'?db()->query('SELECT * FROM opportunities ORDER BY created_at DESC LIMIT 200')->fetchAll():[];
$labels=['new'=>'Nouvelle','in_progress'=>'En cours','connected'=>'Mise en relation','closed'=>'Clôturée','pending'=>'En attente','approved'=>'Approuvée','rejected'=>'Rejetée','draft'=>'Brouillon','published'=>'Publiée'];
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administration — LINKSTECH</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7f8;color:#0c1c2a;font-family:Arial,sans-serif}.layout{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{background:#071a2c;color:#fff;padding:28px 20px}.side h2{margin:0 0 30px}.side a{display:block;color:#b9c8d4;text-decoration:none;padding:12px;border-radius:7px;margin:4px 0}.side a:hover,.side a.active{background:#176bff;color:#fff}.main{padding:35px;overflow:auto}.top{display:flex;justify-content:space-between;align-items:center}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:25px 0}.stat,.panel{background:#fff;padding:24px;border-radius:13px;box-shadow:0 6px 25px #071a2c0d}.stat strong{display:block;font-size:35px;color:#176bff}.table{width:100%;border-collapse:collapse;background:#fff}.table th,.table td{text-align:left;padding:13px;border-bottom:1px solid #dfe6eb;vertical-align:top;font-size:13px}.table select{padding:7px}.inline{display:flex;gap:6px}button{background:#176bff;color:#fff;border:0;padding:8px 12px;border-radius:6px}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.formgrid input,.formgrid select,.formgrid textarea{width:100%;padding:11px;border:1px solid #dfe6eb;border-radius:7px}.full{grid-column:1/-1}.formgrid textarea{min-height:100px}@media(max-width:850px){.layout{grid-template-columns:1fr}.side{position:static}.cards{grid-template-columns:1fr}.main{padding:20px}.table{display:block;overflow:auto}}
</style></head><body><div class="layout"><aside class="side"><h2>LINKSTECH</h2><a class="<?=$section==='dashboard'?'active':''?>" href="/admin/">Tableau de bord</a><a class="<?=$section==='requests'?'active':''?>" href="?section=requests">Demandes (<?=$counts['requests']?>)</a><a class="<?=$section==='organizations'?'active':''?>" href="?section=organizations">Profils (<?=$counts['organizations']?>)</a><a class="<?=$section==='opportunities'?'active':''?>" href="?section=opportunities">Opportunités</a><a href="/" target="_blank">Voir le site</a><a href="?logout=1">Déconnexion</a></aside><main class="main"><div class="top"><div><h1><?=e(ucfirst($section))?></h1><p>Bienvenue, <?=e($_SESSION['admin_name'])?></p></div></div>
<?php if($section==='dashboard'):?><div class="cards"><div class="stat"><strong><?=$counts['requests']?></strong>Nouvelles demandes</div><div class="stat"><strong><?=$counts['organizations']?></strong>Profils à examiner</div><div class="stat"><strong><?=$counts['opportunities']?></strong>Opportunités publiées</div></div><div class="panel"><h2>Fonctions de la plateforme</h2><p>Gérez les demandes de mise en relation, validez les entreprises, ONG, associations et bailleurs, puis publiez les marchés, financements et partenariats.</p></div>
<?php elseif($section==='requests'):?><table class="table"><tr><th>Contact</th><th>Besoin</th><th>Message</th><th>Date</th><th>Statut</th></tr><?php foreach($requests as $r):?><tr><td><strong><?=e($r['name'])?></strong><br><?=e($r['phone'])?><br><?=e($r['reference_code'])?></td><td><?=e($r['service'])?></td><td><?=nl2br(e($r['message']))?></td><td><?=e($r['created_at'])?></td><td><form class="inline" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="request_status"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status"><?php foreach($allowedRequest as $v):?><option value="<?=$v?>" <?=$r['status']===$v?'selected':''?>><?=e($labels[$v]??$v)?></option><?php endforeach;?></select><button>OK</button></form></td></tr><?php endforeach;?></table>
<?php elseif($section==='organizations'):?><table class="table"><tr><th>Organisation</th><th>Coordonnées</th><th>Présentation / besoin</th><th>Statut</th></tr><?php foreach($organizations as $o):?><tr><td><strong><?=e($o['name'])?></strong><br><?=e($o['organization_type'])?> · <?=e($o['country'])?></td><td><?=e($o['email'])?><br><?=e($o['phone'])?></td><td><?=nl2br(e($o['description']))?><hr><?=nl2br(e($o['needs']))?></td><td><form class="inline" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="org_status"><input type="hidden" name="id" value="<?=$o['id']?>"><select name="status"><?php foreach($allowedOrg as $v):?><option value="<?=$v?>" <?=$o['status']===$v?'selected':''?>><?=e($labels[$v]??$v)?></option><?php endforeach;?></select><button>OK</button></form></td></tr><?php endforeach;?></table>
<?php elseif($section==='opportunities'):?><div class="panel"><h2>Publier une opportunité</h2><form class="formgrid" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create_opportunity"><input name="title" placeholder="Titre" required><select name="category"><option value="market">Marché</option><option value="service">Service</option><option value="funding">Financement</option><option value="partnership">Partenariat</option><option value="training">Formation</option></select><input name="organization" placeholder="Organisation" required><input name="country" placeholder="Pays" required><input type="email" name="email" placeholder="E-mail de contact"><input type="date" name="deadline"><textarea class="full" name="description" placeholder="Description" required></textarea><button>Publier</button></form></div><br><table class="table"><tr><th>Titre</th><th>Catégorie</th><th>Organisation</th><th>Statut</th></tr><?php foreach($opportunities as $o):?><tr><td><?=e($o['title'])?></td><td><?=e($o['category'])?></td><td><?=e($o['organization_name'])?> · <?=e($o['country'])?></td><td><form class="inline" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="opp_status"><input type="hidden" name="id" value="<?=$o['id']?>"><select name="status"><?php foreach($allowedOpp as $v):?><option value="<?=$v?>" <?=$o['status']===$v?'selected':''?>><?=e($labels[$v]??$v)?></option><?php endforeach;?></select><button>OK</button></form></td></tr><?php endforeach;?></table><?php endif;?></main></div></body></html>
