<?php
declare(strict_types=1);
require __DIR__ . '/platform-bootstrap.php';
if (!platform_installed()) { header('Location: /install.php'); exit; }
$categories=['market'=>'Marché','service'=>'Service','funding'=>'Financement','partnership'=>'Partenariat','training'=>'Formation'];
$filter=clean_text($_GET['category']??'',30);
$sql="SELECT * FROM opportunities WHERE status='published' AND (deadline IS NULL OR deadline >= CURDATE())";
$params=[];
if(isset($categories[$filter])){$sql.=' AND category=?';$params[]=$filter;}
$sql.=' ORDER BY created_at DESC'; $q=db()->prepare($sql);$q->execute($params);$items=$q->fetchAll();
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Opportunités — LINKSTECH</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7f8;color:#0c1c2a;font-family:Arial,sans-serif}.hero{background:#071a2c;color:#fff;padding:25px 0 65px}.inner{width:min(1100px,92%);margin:auto}.nav{display:flex;justify-content:space-between}.nav a{color:#fff;text-decoration:none}.hero h1{font-size:clamp(35px,6vw,65px);margin:60px 0 12px}.hero p{color:#cfdae2;max-width:650px;line-height:1.6}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:30px 0}.filters a{padding:9px 14px;background:#fff;border-radius:30px;text-decoration:none;color:#60707f}.filters a.active{background:#176bff;color:#fff}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;padding-bottom:60px}.card{background:#fff;padding:25px;border-radius:14px;box-shadow:0 8px 30px #071a2c12}.tag{color:#176bff;font-weight:700;font-size:12px;text-transform:uppercase}.card h2{margin:12px 0}.card p{color:#60707f;line-height:1.6}.meta{font-size:13px;border-top:1px solid #dfe6eb;padding-top:15px}.empty{background:#fff;padding:35px;border-radius:14px}.cta{display:inline-block;background:#f6b73c;color:#071a2c;padding:12px 18px;border-radius:8px;text-decoration:none;font-weight:700}@media(max-width:700px){.grid{grid-template-columns:1fr}}
</style></head><body><header class="hero"><div class="inner"><div class="nav"><strong>LINKSTECH</strong><div><a href="/">Accueil</a> · <a href="/register.php">Rejoindre la plateforme</a></div></div><h1>Opportunités</h1><p>Découvrez les marchés, services, financements, partenariats et formations partagés par LINKSTECH.</p></div></header><main class="inner"><div class="filters"><a class="<?=!$filter?'active':''?>" href="/opportunities.php">Toutes</a><?php foreach($categories as $key=>$label):?><a class="<?=$filter===$key?'active':''?>" href="?category=<?=e($key)?>"><?=e($label)?></a><?php endforeach;?></div><?php if(!$items):?><div class="empty"><h2>Aucune opportunité disponible actuellement</h2><p>Inscrivez votre profil pour être informé des prochaines opportunités.</p><a class="cta" href="/register.php">Rejoindre la plateforme</a></div><?php else:?><div class="grid"><?php foreach($items as $item):?><article class="card"><span class="tag"><?=e($categories[$item['category']]??$item['category'])?></span><h2><?=e($item['title'])?></h2><p><?=nl2br(e($item['description']))?></p><div class="meta"><strong><?=e($item['organization_name'])?></strong> · <?=e($item['country'])?><?php if($item['deadline']):?> · Date limite : <?=e(date('d/m/Y',strtotime($item['deadline'])))?><?php endif;?></div></article><?php endforeach;?></div><?php endif;?></main></body></html>
