<?php
declare(strict_types=1);
require __DIR__ . '/platform-bootstrap.php';
if (!platform_installed()) { header('Location: /install.php'); exit; }
$error = ''; $success = false;
$types = ['company'=>'Entreprise technique','startup'=>'Startup / porteur de projet','service_provider'=>'Prestataire de services','ngo'=>'ONG','association'=>'Association','funder'=>'Bailleur de fonds','individual'=>'Particulier'];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $name=clean_text($_POST['name']??'',180); $type=clean_text($_POST['type']??'',30);
    $email=filter_var(trim((string)($_POST['email']??'')),FILTER_VALIDATE_EMAIL);
    $phone=clean_text($_POST['phone']??'',40); $country=clean_text($_POST['country']??'',100);
    $description=clean_text($_POST['description']??'',2000); $needs=clean_text($_POST['needs']??'',2000);
    if(mb_strlen($name)<2 || !$email || mb_strlen($phone)<7 || !$country || mb_strlen($description)<20 || !isset($types[$type])) $error='Veuillez remplir correctement tous les champs obligatoires.';
    else { $q=db()->prepare('INSERT INTO organizations (name,organization_type,email,phone,country,description,needs) VALUES (?,?,?,?,?,?,?)'); $q->execute([$name,$type,$email,$phone,$country,$description,$needs]); $success=true; }
}
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rejoindre la plateforme — LINKSTECH</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7f8;color:#0c1c2a;font-family:Arial,sans-serif}.top{background:#071a2c;color:#fff;padding:22px}.top div{width:min(1050px,92%);margin:auto;display:flex;justify-content:space-between;align-items:center}.top a{color:#fff;text-decoration:none}.wrap{width:min(800px,92%);margin:50px auto}.card{background:#fff;border-radius:16px;padding:34px;box-shadow:0 15px 50px #071a2c18}h1{margin-top:0}p{color:#60707f;line-height:1.6}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field{margin:10px 0}.full{grid-column:1/-1}label{display:block;font-weight:700;font-size:13px;margin-bottom:7px}input,select,textarea{width:100%;padding:13px;border:1px solid #dfe6eb;border-radius:8px}textarea{min-height:120px}button{border:0;background:#176bff;color:#fff;padding:14px 22px;border-radius:8px;font-weight:700}.notice{padding:15px;border-radius:8px;margin-bottom:18px}.error{background:#fff0f0;color:#a21b1b}.ok{background:#edf9f1;color:#176b3a}@media(max-width:650px){.grid{grid-template-columns:1fr}.full{grid-column:auto}.card{padding:22px}}
</style></head><body><header class="top"><div><strong>LINKSTECH</strong><nav><a href="/">Accueil</a> · <a href="/opportunities.php">Opportunités</a></nav></div></header><main class="wrap"><div class="card"><h1>Rejoindre la plateforme</h1><p>Inscrivez votre entreprise, service, ONG, association ou organisation afin d’être connecté aux clients, marchés, partenaires et bailleurs de fonds adaptés.</p><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="notice ok"><strong>Inscription reçue.</strong> Notre équipe examinera votre profil et vous contactera.</div><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="grid"><div class="field full"><label>Nom de l’organisation ou du particulier</label><input name="name" required></div><div class="field"><label>Type de profil</label><select name="type"><?php foreach($types as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></div><div class="field"><label>Pays</label><input name="country" required></div><div class="field"><label>E-mail</label><input type="email" name="email" required></div><div class="field"><label>Téléphone / WhatsApp</label><input name="phone" required></div><div class="field full"><label>Présentation</label><textarea name="description" minlength="20" required placeholder="Décrivez vos activités, services ou missions."></textarea></div><div class="field full"><label>Besoins ou opportunités recherchées</label><textarea name="needs" placeholder="Clients, marchés, financement, partenaire technique, formation..."></textarea></div></div><button type="submit">Envoyer le profil</button></form><?php endif;?></div></main></body></html>
